GITHUB_KEY: "sajldjsadnjaskldjkc121"
GITHUB_SECRET: "541sdasdakjcksacmk"

TWITTER_KEY:
TWITTER_SECRET:

ALGOLIASEARCH_APPLICATION_ID:
ALGOLIASEARCH_SEARCH_ONLY_KEY:
ALGOLIASEARCH_API_KEY:

PUSHER_APP_ID:
PUSHER_KEY:
PUSHER_SECRET:
PUSHER_CLUSTER:

TWITCH_CLIENT_ID:
TWITCH_CLIENT_SECRET:
TWITCH_WEBHOOK_SECRET:

REDIS_URL: "redis://redis:6379"
REDIS_SESSIONS_URL: "redis://redis:6379"
